import json
import logging
from typing import AsyncGenerator

from fastapi import APIRouter
from fastapi.responses import StreamingResponse

from app.dependencies import LLMDep, RetrievalDep, SynthesisDep
from app.models.chat import ChatRequest, ChatResponse, NoteSource, RagChatRequest, RagChatResponse
from app.services.llm.schemas import ChatCompletionRequest, LLMMessage, LLMOptions
from app.services.retrieval.models import RetrievalQuery
from app.services.vector.models import SearchFilter

router = APIRouter()
logger = logging.getLogger("app.api.chat")


def _to_llm_messages(request: ChatRequest) -> list[LLMMessage]:
    """Convert public API messages to internal LLM messages.

    The API layer only exposes 'user' and 'assistant' roles. System prompts
    are injected server-side here. This prevents clients from overriding the
    system prompt (a common prompt-injection vector).
    """
    system = LLMMessage(
        role="system",
        content=(
            "You are a helpful AI assistant for a personal knowledge base. "
            "Answer questions based on the user's notes. "
            "If you are unsure, say so clearly rather than fabricating information."
        ),
    )
    history = [LLMMessage(role=m.role, content=m.content) for m in request.messages]
    return [system, *history]


@router.post("", response_model=ChatResponse, summary="Send a chat message")
async def chat(request: ChatRequest, llm: LLMDep) -> ChatResponse:
    """Blocking chat completion.

    Waits for the full response before returning. Use /chat/stream for
    progressive rendering in the UI.
    """
    llm_request = ChatCompletionRequest(
        model=llm.chat_model,  # type: ignore[attr-defined]
        messages=_to_llm_messages(request),
        options=LLMOptions(),
    )
    completion = await llm.chat(llm_request)
    logger.info(
        "Chat completed",
        extra={
            "model": completion.model,
            "prompt_tokens": completion.prompt_tokens,
            "completion_tokens": completion.completion_tokens,
            "duration_ms": completion.total_duration_ms,
        },
    )
    return ChatResponse(content=completion.content, sources=[])


@router.post(
    "/stream",
    summary="Send a chat message (streaming SSE)",
    description=(
        "Server-Sent Events stream. Each event is a JSON object:\n\n"
        "- `{\"delta\": \"token\", \"done\": false}` — next token chunk\n"
        "- `{\"delta\": \"\", \"done\": true}` — stream finished\n\n"
        "Connect with `EventSource` or a `fetch` + `ReadableStream`."
    ),
    response_class=StreamingResponse,
)
async def chat_stream(request: ChatRequest, llm: LLMDep) -> StreamingResponse:
    """Streaming chat — yields tokens as they are generated by Ollama.

    SSE wire format:  data: {...}\\n\\n  (double newline terminates each event)
    Headers:
      Cache-Control: no-cache       — prevents proxies caching partial events
      X-Accel-Buffering: no         — disables nginx response buffering
      Connection: keep-alive        — keeps the TCP connection open
    """
    llm_request = ChatCompletionRequest(
        model=llm.chat_model,  # type: ignore[attr-defined]
        messages=_to_llm_messages(request),
        options=LLMOptions(),
    )

    async def _sse_generator() -> AsyncGenerator[bytes, None]:
        stream = await llm.chat_stream(llm_request)
        async for delta in stream:
            event = {"delta": delta.content, "done": delta.done}
            yield f"data: {json.dumps(event)}\n\n".encode()
            if delta.done:
                break

    return StreamingResponse(
        _sse_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


@router.post("/rag", response_model=RagChatResponse, summary="RAG chat — answers grounded in vault notes")
async def rag_chat(
    request: RagChatRequest,
    retrieval: RetrievalDep,
    synthesizer: SynthesisDep,
) -> RagChatResponse:
    """Retrieval-augmented chat.

    1. Embeds the last user message and retrieves the top-k matching chunks
       from the Qdrant vault index.
    2. Passes the retrieved chunks to LlamaIndex's response synthesizer, which
       compacts context and generates an answer grounded in the note excerpts.
    3. Returns the answer together with source attribution and observability
       fields (latency, candidate count, dedup count).

    Use this endpoint for question-answering over the knowledge base.
    Use POST /chat for plain LLM chat with no retrieval.
    """
    question = request.messages[-1].content

    filters: SearchFilter | None = None
    if request.tags or request.note_path:
        filters = SearchFilter(tags=request.tags or [], note_path=request.note_path)

    retrieval_result = await retrieval.retrieve(
        RetrievalQuery(
            text=question,
            top_k=request.top_k,
            score_threshold=request.score_threshold,
            filters=filters,
            deduplicate=request.deduplicate,
        )
    )

    synthesis_result = await synthesizer.synthesize(question, retrieval_result.chunks)

    sources = [
        NoteSource(
            note_title=c.note_title,
            note_path=c.note_path,
            excerpt=c.chunk_text[:300],
            score=c.score,
        )
        for c in synthesis_result.source_chunks
    ]

    logger.info(
        "RAG chat complete",
        extra={
            "question": question[:120],
            "sources": len(sources),
            "retrieval_ms": retrieval_result.latency_ms,
            "synthesis_ms": synthesis_result.latency_ms,
        },
    )

    return RagChatResponse(
        content=synthesis_result.answer,
        sources=sources,
        retrieval_latency_ms=retrieval_result.latency_ms,
        synthesis_latency_ms=synthesis_result.latency_ms,
        total_candidates=retrieval_result.total_candidates,
        deduplicated_count=retrieval_result.deduplicated_count,
        filters_applied=retrieval_result.filters_applied,
    )
